version: "3"
#Laravel App
services:
  app:
    # used build to map each build of each services into a specific Dockerfile to proceed a specific image
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
      - appnetwork
  server:
    container_name: server
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - appnetwork
    depends_on:
      - app
  mysql:

    image: mysql:5.7
    container_name: database
    tty: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=quuV44{7g>oz]AT2bd
      - MYSQL_USER=dc
      - MYSQL_PASSWORD=4A)2L=v2?ucTJDJ9fj
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnetwork
  myadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    restart: always
    depends_on:
      - mysql
    volumes:
      - /sessions
#Docker Networks
networks:
  appnetwork:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
